12-CSharp-ASP.NET-MVC-Overview-Lab/TODOList/TODOList/Models/Task.cs
using System.ComponentModel.DataAnnotations;

namespace TODOList.Models
{
    public class Task
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }
    }
}

12-CSharp-ASP.NET-MVC-Overview-Lab/TODOList/TODOList/Models/TaskDbContext.cs
namespace TODOList.Models
{
    using System.Data.Entity;

    public class TaskDbContext : DbContext
    {
        public TaskDbContext()
            : base("name=TaskDbContext")
        {
        }

        public virtual DbSet<Task> Tasks { get; set; }
    }
}

12-CSharp-ASP.NET-MVC-Overview-Lab/TODOList/TODOList/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using TODOList.Models;

namespace TODOList.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            using (var db = new TaskDbContext())
            {
                var tasks = db.Tasks.ToList();

                return View(tasks);
            }
        }
    }
}

12-CSharp-ASP.NET-MVC-Overview-Lab/TODOList/TODOList/Controllers/TaskController.cs
using System.Web.Mvc;
using TODOList.Models;

namespace TODOList.Controllers
{
    public class TaskController : Controller
    {
        [HttpPost]
        public ActionResult Create(Task task)
        {

            int a = 0;

            if (task.Title == null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var db = new TaskDbContext())
            {
                db.Tasks.Add(task);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var db = new TaskDbContext())
            {
                var task = db.Tasks.Find(id);

                if (task == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                db.Tasks.Remove(task);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

12-CSharp-ASP.NET-MVC-Overview-Lab/TODOList/TODOList/Views/Home/Index.cshtml
@model List<TODOList.Models.Task>
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h3>TODO List</h3>
        <ol>
            @foreach (var task in Model)
            {
                <li>@task.Title @Html.ActionLink("[Delete]", "Delete", "Task", htmlAttributes: null, routeValues: new { id = task.Id })</li>
            }
        </ol>
        @using (Html.BeginForm("Create", "Task", null, FormMethod.Post, new { @class = "form-inline" }))
        {
            <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="Task Title" autofocus="autofocus" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Add Task" />
            </div>
        }
    </div>
</div>