Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Models/LogNozirohDbContext.cs
namespace LogNoziroh.Models
{
    using System.Data.Entity;
    public class LogNozirohDbContext : DbContext
    {
        public virtual IDbSet<Report> Reports { get; set; }

        public LogNozirohDbContext() : base("LogNoziroh")
        {
        }
    }
}

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Models/Report.cs
namespace LogNoziroh.Models
{
    using System.ComponentModel.DataAnnotations;

    public class Report
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Status { get; set; }

        [Required]
        public string Message { get; set; }

        [Required]
        public string Origin { get; set; }
    }
}

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Controllers/ReportController.cs
namespace LogNoziroh.Controllers
{
    using Models;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;

    [ValidateInput(false)]
    public class ReportController : Controller
    {
        private LogNozirohDbContext db = new LogNozirohDbContext();

        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            var reports = db.Reports.ToList();

            return View(reports);
        }

        [HttpGet]
        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            var report = db.Reports.Find(id);

            if (report == null)
            {
                return Redirect("/");
            }

            return View(report);
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateConfrim(Report report)
        {
            if (ModelState.IsValid)
            {
                db.Reports.Add(report);
                db.SaveChanges();
            }

            return Redirect("/");
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult Edit(int id)
        {
            var report = db.Reports.Find(id);

            if (report == null)
            {
                return Redirect("/");
            }

            return View(report);
        }

        [HttpPost]
        [Route("edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirm([Bind(Include = "Id,Status,Message,Origin")] Report report)
        {
            if (ModelState.IsValid)
            {
                db.Entry(report).State = EntityState.Modified;
                db.SaveChanges();
            }

            return Redirect("/");
        }

        [HttpGet]
        [Route("delete/{id}")]
        public ActionResult Delete(int id)
        {
            var report = db.Reports.Find(id);

            if (report == null)
            {
                return Redirect("/");
            }

            return View(report);
        }

        [HttpPost]
        [Route("delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var report = db.Reports.Find(id);

            if (report == null)
            {
                return Redirect("/");
            }

            db.Reports.Remove(report);
            db.SaveChanges();

            return Redirect("/");
        }
    }
}

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Views/Report/Create.cshtml
@model LogNoziroh.Models.Report

@{
    ViewBag.Title = "Create";
}

<div class="wrapper">
    @using (Html.BeginForm("Create", "Report", FormMethod.Post, new { @class = "report-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Log Report
        </div>
        <div class="create-status">
            <div class="create-status-label">Status</div>
            <div class="create-status-content">
                <input type="radio" id="normal-status" name="status" value="Normal" checked="checked"/>
                <label for="normal-status">Normal</label>
                <input type="radio" id="warning-status" name="status" value="Warning" />
                <label for="warning-status">Warning</label>
                <input type="radio" id="critical-status" name="status" value="Critical" />
                <label for="critical-status">Critical</label>
            </div>
        </div>
        <div class="create-message">
            <div class="create-message-label">Message</div>
            <textarea rows="3" class="create-message-content" type="text" name="message"></textarea>
        </div>
        <div class="create-origin">
            <div class="create-origin-label">Origin</div>
            <textarea rows="3" class="create-origin-content" type="text" name="origin"></textarea>
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Log Report</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Views/Report/Delete.cshtml
@model LogNoziroh.Models.Report

@{
    ViewBag.Title = "Delete";
}

<div class="wrapper">
    @using (Html.BeginForm("Delete", "Report", FormMethod.Post, new { @class="report-create"} ))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Archive Report
        </div>
        <div class="create-status">
            <div class="create-status-label">Status</div>
            <div class="create-status-content">
                <input type="radio" id="normal-status" name="status" value="Normal" @(Model.Status == "Normal" ? "checked" : "") disabled />
                <label for="normal-status">Normal</label>
                <input type="radio" id="warning-status" name="status" value="Warning" @(Model.Status == "Warning" ? "checked" : "") disabled />
                <label for="warning-status">Warning</label>
                <input type="radio" id="critical-status" name="status" value="Critical" @(Model.Status == "Critical" ? "checked" : "") disabled />
                <label for="critical-status">Critical</label>
            </div>
        </div>
        <div class="create-message">
            <div class="create-message-label">Message</div>
            <textarea rows="3" class="create-message-content" name="message" disabled>@(Model.Message)</textarea>
        </div>
        <div class="create-origin">
            <div class="create-origin-label">Origin</div>
            <textarea rows="3" class="create-origin-content" name="origin" disabled>@(Model.Origin)</textarea>
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Archive Report</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Views/Report/Details.cshtml
@model LogNoziroh.Models.Report

@{
    ViewBag.Title = "Details";
}

<div class="wrapper">
    <div class="report-details">
        <div class="details-header">
            Report Details
        </div>
        <div class="details-status">
            <div class="details-status-label">Status</div>
            <div class="details-status-content">@(Model.Status)</div>
        </div>
        <div class="details-message">
            <div class="details-message-label">Message</div>
            <div class="details-message-content">
                @(Model.Message)
            </div>
        </div>
        <div class="details-origin">
            <div class="details-origin-label">Origin</div>
            <div class="details-origin-content">
                @(Model.Origin)
            </div>
        </div>
    </div>
    <div class="details-button-holder">
        <a type="button" href="/" class="back-button">Back</a>
    </div>
</div>

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Views/Report/Edit.cshtml
@model LogNoziroh.Models.Report

@{
    ViewBag.Title = "Edit";
}

<div class="wrapper">
    @using (Html.BeginForm("Edit", "Report", FormMethod.Post, new { @class = "report-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Edit Report
        </div>
        <div class="create-status">
            <div class="create-status-label">Status</div>
            <div class="create-status-content">
                <input type="radio" id="normal-status" name="status" value="Normal" @(Model.Status == "Normal" ? "checked" : "") />
                <label for="normal-status">Normal</label>
                <input type="radio" id="warning-status" name="status" value="Warning" @(Model.Status == "Warning" ? "checked" : "") />
                <label for="warning-status">Warning</label>
                <input type="radio" id="critical-status" name="status" value="Critical" @(Model.Status == "Critical" ? "checked" : "") />
                <label for="critical-status">Critical</label>
            </div>
        </div>
        <div class="create-message">
            <div class="create-message-label">Message</div>
            <textarea rows="3" class="create-message-content" type="text" name="message">@(Model.Message)</textarea>
        </div>
        <div class="create-origin">
            <div class="create-origin-label">Origin</div>
            <textarea rows="3" class="create-origin-content" type="text" name="origin">@(Model.Origin)</textarea>
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Edit Report</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Views/Report/Index.cshtml
@model List<LogNoziroh.Models.Report>

@{
	ViewBag.Title = "Index";
}

<div class="wrapper">
    <div class="button-holder">
        <a type="button" href="/create" class="log-button">Log New Report</a>
    </div>
    <div class="content">
        <div class="header">
            <div class="message-label">Message</div>
            <div class="actions-label">Actions</div>
        </div>
        <div class="main">
            @foreach (var report in Model.ToList())
            {
                <div class="report @(report.Status.ToLower())-report">
                    <div class="report-message">
                        @(report.Message.Length > 50 ? report.Message.Substring(0, 50) + "..." : report.Message)
                    </div>
                    <div class="report-actions">
                        @Html.ActionLink("Edit", "Edit", "Report", new { id = report.Id }, new { @class = "details-button" })
                        @Html.ActionLink("Delete", "Delete", "Report", new { id = report.Id }, new { @class = "delete-button" })
                        @Html.ActionLink("Details", "Details", "Report", new { id = report.Id }, new { @class = "details-button" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Exams/Exam-21-Dec-2017/CSharp/LogNoziroh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>LogNoziroh</title>
	@Styles.Render("~/Content/reset.css")
	@Styles.Render("~/Content/style.css")
	@Styles.Render("~/Content/details-style.css")
	@Styles.Render("~/Content/create-style.css")
</head>
<body>
	@RenderBody()
</body>
</html>