13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Models/Article.cs
namespace SoftUniBlog.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Article
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime Date { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public bool IsAuthor(string authorId)
        {
            return AuthorId == authorId;
        }
    }
}

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Models/ArticleViewModel.cs
namespace SoftUniBlog.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class ArticleViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime Date { get; set; }

        public string AuthorId { get; set; }
    }
}

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Controllers/ArticleController.cs
namespace SoftUniBlog.Controllers
{
    using Microsoft.AspNet.Identity;
    using Models;
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    public class ArticleController : Controller
    {
        [ActionName("List")]
        [HttpGet]
        public ActionResult ListView()
        {
            using (var db = new BlogDbContext())
            {
                var articles = db.Articles
                    .Include(a => a.Author)
                    .OrderByDescending(d => d.Date)
                    .Take(6)
                    .ToList();

                foreach (var article in articles)
                {
                    article.Content = article
                        .Content
                        .Substring(0, article.Content.Length / 2) + "...";
                }

                return View(articles);
            }
        }

        [Authorize]
        [ActionName("Create")]
        [HttpGet]
        public ActionResult CreateView()
        {
            return View();
        }

        [Authorize]
        [ActionName("Create")]
        [HttpPost]
        public ActionResult CreateAction(Article model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new BlogDbContext())
                {
                    var authorId = User.Identity.GetUserId();

                    model.AuthorId = authorId;
                    model.Date = DateTime.Now;

                    db.Articles.Add(model);
                    db.SaveChanges();
                }

                return RedirectToAction("List");
            }

            return View(model);
        }

        [ActionName("Details")]
        [HttpGet]
        public ActionResult DetailsView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new BlogDbContext())
            {
                var article = db.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();

                if (article == null)
                {
                    return HttpNotFound();
                }

                return View(article);
            }
        }

        [Authorize]
        [ActionName("Edit")]
        [HttpGet]
        public ActionResult EditView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new BlogDbContext())
            {
                var article = db.Articles.Find(id);

                if (!IsAuthorized(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                if (article == null)
                {
                    return HttpNotFound();
                }

                var model = new ArticleViewModel
                {
                    Id = article.Id,
                    Title = article.Title,
                    Content = article.Content,
                    AuthorId = article.AuthorId
                };

                return View(model);
            }
        }

        [Authorize]
        [ActionName("Edit")]
        [HttpPost]
        public ActionResult EditAction(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new BlogDbContext())
                {
                    var article = db.Articles.Find(model.Id);

                    if (!IsAuthorized(article))
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                    }

                    if (article == null)
                    {
                        return HttpNotFound();
                    }

                    article.Title = model.Title;
                    article.Content = model.Content;
                    article.Date = DateTime.Now;

                    db.Entry(article).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("List");
                }
            }

            return View(model);
        }

        [Authorize]
        [ActionName("Delete")]
        [HttpGet]
        public ActionResult DeleteView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new BlogDbContext())
            {
                var article = db.Articles.Find(id);

                if (!IsAuthorized(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                if (article == null)
                {
                    return HttpNotFound();
                }

                return View(article);
            }
        }

        [Authorize]
        [ActionName("Delete")]
        [HttpPost]
        public ActionResult DeleteAction(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new BlogDbContext())
            {
                var article = db.Articles.Find(id);

                if (!IsAuthorized(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                if (article == null)
                {
                    return HttpNotFound();
                }

                db.Articles.Remove(article);
                db.SaveChanges();

                return RedirectToAction("List");
            }
        }

        private bool IsAuthorized(Article model)
        {
            var isAdmin = User.IsInRole("Admin");
            var isAuthor = model.IsAuthor(User.Identity.GetUserId());

            return isAdmin || isAuthor;
        }
    }
}

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Views/Article/Create.cshtml
@model SoftUniBlog.Models.Article
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create Article</h2>
        @using (Html.BeginForm("Create", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "List", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Views/Article/Delete.cshtml
@model SoftUniBlog.Models.Article

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Article</h2>
        @using (Html.BeginForm("Delete", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "List", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Views/Article/Details.cshtml
@using Microsoft.AspNet.Identity
@model SoftUniBlog.Models.Article

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <article>
        <header>
            <h2>
                @Model.Title
            </h2>
        </header>
        <p>
            @Model.Content
        </p>
        <small class="author">
            Author: @Model.Author.FullName
        </small>
        <small>
            Last Edit: @Model.Date
        </small>
        <footer class="pull-right">
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin") || Model.IsAuthor(User.Identity.GetUserId()))
            {
                @Html.ActionLink("Edit", "Edit", "Article", new {@id = Model.Id}, new {@class = "btn btn-success btn-xs"})
                @Html.ActionLink("Delete", "Delete", "Article", new {@id = Model.Id}, new {@class = "btn btn-danger btn-xs"})
            }

            @Html.ActionLink("Back", "List", "Article", null, new {@class = "btn btn-default btn-xs"})
        </footer>
    </article>
</div>
<hr />

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Views/Article/Edit.cshtml
@model SoftUniBlog.Models.ArticleViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="well">
        <h2>Edit Article</h2>
        @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "List", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

13-CSharp-Blog-Basic-Functionality/SoftUniBlog/Views/Article/List.cshtml
@model List<SoftUniBlog.Models.Article>

@{
    ViewBag.Title = "List";
}

<div class="container">
    <div class="row">
        @foreach (var article in Model)
        {
            <div class="col-sm-6">
                <article>
                    <header>
                        <h2>
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </h2>
                    </header>
                    <p>
                        @article.Content
                    </p>
                    <footer>
                        <small class="author">
                            Author: @article.Author.FullName
                        </small>
                        <small>
                            Last Edit: @article.Date
                        </small>
                    </footer>
                </article>
            </div>
        }
    </div>
</div>
<hr />